import { Hero } from './hero.model';

export const HEROES_MOCK_LIST: Hero[] = [
  {
    id: 1,
    name: 'Superman',
    powers: [
      'Superhuman Strength',
      'Superhuman Speed',
      'Superhuman Stamina',
      'Superhuman Durability',
      'Flight',
      'Heat Vision',
      'Freeze Breath',
      'Super Breath',
      'Superhuman Hearing',
      'Superhuman Vision',
    ],
  },
  {
    id: 2,
    name: 'Batman',
    powers: [
      'Genius-Level Intellect',
      'Peak Human Physical Condition',
      'Master Martial Artist',
      'Expert Detective',
      'Utilizes High-Tech Equipment and Weapons',
    ],
  },
  {
    id: 3,
    name: 'Wonder Woman',
    powers: [
      'Superhuman Strength',
      'Superhuman Speed',
      'Superhuman Agility',
      'Superhuman Durability',
      'Flight',
      'Enhanced Senses (including Superhuman Hearing and Vision)',
      'Healing Factor',
    ],
  },
  {
    id: 4,
    name: 'Green Lantern (Hal Jordan)',
    powers: [
      'Energy Projection and Constructs (via Power Ring)',
      'Flight (via Power Ring)',
      'Force Field Generation (via Power Ring)',
      'Energy Absorption (via Power Ring)',
      'Energy Blasts (via Power Ring)',
      'Energy Constructs (via Power Ring)',
    ],
  },
  {
    id: 5,
    name: 'The Flash (Barry Allen)',
    powers: [
      'Superhuman Speed',
      'Time Travel',
      'Phasing/Intangibility',
      'Speed Force Aura (protects from harm while moving at superhuman speed)',
      'Increased Perceptions',
    ],
  },
  {
    id: 6,
    name: 'Aquaman',
    powers: ['Social Influencer', 'Control Over Marine Life', 'Endurance', 'Enhanced Senses', 'Superhuman Strength', 'Telepathy'],
  },
  {
    id: 7,
    name: 'Martian Manhunter',
    powers: [
      'Superhuman Strength',
      'Superhuman Speed',
      'Flight',
      'Intangibility',
      'Invisibility',
      'Telepathy',
      'Telekinesis',
      'Shape-Shifting',
    ],
  },
  {
    id: 8,
    name: 'Doctor Fate (Kent Nelson)',
    powers: ['Magic Manipulation', 'Flight', 'Teleportation', 'Telekinesis', 'Energy Projection and Constructs'],
  },
  {
    id: 9,
    name: 'Hawkman (Carter Hall)',
    powers: ['Flight via Nth Metal Wings and Harness', 'Enhanced Strength, Speed, Agility, and Durability via Nth Metal Armor and Harness'],
  },
  {
    id: 10,
    name: 'Green Arrow (Oliver Queen)',
    powers: ['Peak Human Physical Condition', 'Master Archer and Marksman', 'Expert Combatant'],
  },
  {
    id: 11,
    name: 'Black Canary (Dinah Laurel Lance)',
    powers: ['Canary Cry: Ultrasonic scream capable of incapacitating foes or objects'],
  },
  {
    id: 12,
    name: 'Atom (Ray Palmer)',
    powers: ['Size Alteration: Can shrink down to subatomic size or grow to giant size'],
  },
  {
    id: 13,
    name: '(The) Spectre (Jim Corrigan)',
    powers: ['(Divine) Omnipotence: Can manipulate reality, time, space, matter, energy, souls, etc.'],
  },
  {
    id: 14,
    name: '(The) Question (Vic Sage)',
    powers: ['(Martial) Arts Mastery: Expert in multiple forms of martial arts'],
  },
  {
    id: 15,
    name: '(The) Sandman (Wesley Dodds)',
    powers: ["(Dream) Control: Can enter people's dreams and manipulate them"],
  },
  {
    id: 16,
    name: '(The) Flash (Jay Garrick)',
    powers: ['(Speed) Force Manipulation: Can manipulate the Speed Force to enhance his speed and other abilities'],
  },
  {
    id: 17,
    name: 'Green Lantern (John Stewart)',
    powers: [
      'Energy Projection and Constructs (via Power Ring)',
      'Flight (via Power Ring)',
      'Force Field Generation (via Power Ring)',
      'Energy Absorption (via Power Ring)',
      'Energy Blasts (via Power Ring)',
      'Energy Constructs (via Power Ring)',
    ],
  },
  {
    id: 18,
    name: 'Black Lightning (Jefferson Pierce)',
    powers: ['Electrokinesis', 'Flight', 'Force Field Generation', 'Superhuman Strength', 'Superhuman Durability'],
  },
  {
    id: 19,
    name: '(The) Atom (Ryan Choi)',
    powers: ['Size Alteration: Can shrink down to subatomic size or grow to giant size'],
  },
  {
    id: 20,
    name: 'Batgirl (Barbara Gordon)',
    powers: ['Peak Human Physical Condition', 'Expert Combatant', 'Expert Detective', 'Genius-Level Intellect'],
  },
  {
    id: 21,
    name: 'Cyborg (Victor Stone)',
    powers: [
      'Superhuman Strength',
      'Superhuman Durability',
      'Regenerative Healing Factor',
      'Technopathy',
      'Energy Projection and Absorption',
    ],
  },
  {
    id: 22,
    name: "(The) Martian Manhunter (J'onn J'onzz)",
    powers: [
      'Superhuman Strength',
      'Superhuman Speed',
      'Flight',
      'Intangibility',
      'Invisibility',
      'Telepathy',
      'Telekinesis',
      'Shape-Shifting',
    ],
  },
  {
    id: 23,
    name: '(The) Spectre (Aztar)',
    powers: ['(Divine) Omnipotence: Can manipulate reality, time, space, matter, energy, souls, etc.'],
  },
  {
    id: 24,
    name: '(The) Question (Renee Montoya)',
    powers: ['(Martial) Arts Mastery: Expert in multiple forms of martial arts'],
  },
  {
    id: 25,
    name: '(The) Sandman (Daniel Hall)',
    powers: ["(Dream) Control: Can enter people's dreams and manipulate them"],
  },
  {
    id: 26,
    name: 'Zatanna',
    powers: ['Magic Manipulation', 'Flight', 'Teleportation', 'Telekinesis', 'Energy Projection and Constructs'],
  },
  {
    id: 27,
    name: '(The) Atom (Al Pratt)',
    powers: ['Superhuman Strength', 'Superhuman Durability'],
  },
  {
    id: 28,
    name: '(The) Flash (Wally West)',
    powers: [
      'Superhuman Speed',
      'Time Travel',
      'Phasing/Intangibility',
      'Speed Force Aura (protects from harm while moving at superhuman speed)',
      'Increased Perceptions',
    ],
  },
  {
    id: 29,
    name: 'Batwoman (Kate Kane)',
    powers: ['Peak Human Physical Condition', 'Expert Combatant', 'Expert Detective', 'Genius-Level Intellect'],
  },
  {
    id: 30,
    name: 'Cyborg Superman (Hank Henshaw)',
    powers: [
      'Superhuman Strength',
      'Superhuman Durability',
      'Regenerative Healing Factor',
      'Technopathy',
      'Energy Projection and Absorption',
    ],
  },
];
